<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Interstitial Pass /n]]>
    </line>
    <line>
      <![CDATA[Some problem came in Login]]>
    </line>
  </reporter-output>
  <suite name="SanityWap" duration-ms="104123" started-at="2015-04-06T10:12:17Z" finished-at="2015-04-06T10:14:01Z">
    <groups>
    </groups>
    <test name="intertialScreen" duration-ms="104123" started-at="2015-04-06T10:12:17Z" finished-at="2015-04-06T10:14:01Z">
      <class name="com.mb.wapsanity.testscripts.LaunchWap">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.mb.wapsanity.testscripts.LaunchWap@2ff4f00f]" name="setUp" is-config="true" duration-ms="12584" started-at="2015-04-06T15:42:04Z" finished-at="2015-04-06T15:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.mb.wapsanity.testscripts.LaunchWap -->
      <class name="com.mb.wapsanity.testscripts.LoginAndRegistrationTest">
        <test-method status="PASS" signature="before()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="before" is-config="true" duration-ms="6389" started-at="2015-04-06T15:42:17Z" finished-at="2015-04-06T15:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="intertialScreen()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="intertialScreen" duration-ms="677" started-at="2015-04-06T15:42:23Z" finished-at="2015-04-06T15:42:24Z">
          <reporter-output>
            <line>
              <![CDATA[Interstitial Pass /n]]>
            </line>
          </reporter-output>
        </test-method> <!-- intertialScreen -->
        <test-method status="PASS" signature="registration()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="registration" duration-ms="66932" started-at="2015-04-06T15:42:24Z" finished-at="2015-04-06T15:43:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="logout" duration-ms="30079" started-at="2015-04-06T15:43:31Z" finished-at="2015-04-06T15:44:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logout expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logout expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mb.wapsanity.testscripts.LoginAndRegistrationTest.logout(LoginAndRegistrationTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="FAIL" signature="loginCase()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="loginCase" duration-ms="15" started-at="2015-04-06T15:44:01Z" finished-at="2015-04-06T15:44:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mb.wapsanity.testscripts.LoginAndRegistrationTest.loginCase(LoginAndRegistrationTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Some problem came in Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginCase -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mb.wapsanity.testscripts.LoginAndRegistrationTest@7dc36524]" name="tearDown" is-config="true" duration-ms="0" started-at="2015-04-06T15:44:01Z" finished-at="2015-04-06T15:44:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mb.wapsanity.testscripts.LoginAndRegistrationTest -->
    </test> <!-- intertialScreen -->
  </suite> <!-- SanityWap -->
</testng-results>
